version: '3'
services:
  kuosel-back:
    image: ghcr.io/jesusamador-dev/kuosel-back:latest
    ports:
      - 8000:8000
    restart: always
    networks:
      - network_kuosel
    environment:
      - DATABASE_HOST=${ HOST }
      - DATABASE_NAME=${ DATABASE_NAME }
      - DATABASE_USER=${ DATABASE_USER }
      - DATABASE_PASSWORD=${ DATABASE_PASSWORD }

  mysql:
    image: mysql:latest
    restart: always
    networks:
      - network_kuosel
    environment:
      - MYSQL_DATABASE=${ DATABASE_NAME }
      - MYSQL_USER=${ DATABASE_USER }
      - MYSQL_PASSWORD=${ DATABASE_PASSWORD }
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

networks:
    network_kuosel:

volumes:
  mysql-data:
