version: '3'
services:
  backend:
    image: kuosel-back
    ports:
      - 8000:8000
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=kuosel_db
      - DB_USER=kuosel_user
      - DB_PASSWORD=kuosel_password
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=kuosel_db
      - MYSQL_USER=kuosel_user
      - MYSQL_PASSWORD=kuosel_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: